# Generated by Django 3.2.7 on 2021-10-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic_breast_2',
            name='Date',
        ),
    ]
