# Generated by Django 3.2.7 on 2021-10-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_remove_diagnostic_breast_2_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_breast_2',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
