# Generated by Django 3.2.7 on 2021-10-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_user_nb_alertes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nb_alertes',
            field=models.IntegerField(default=0),
        ),
    ]
