# Generated by Django 3.2.7 on 2021-10-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_user_nb_alertes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nb_patients',
            field=models.IntegerField(default=0),
        ),
    ]
